export enum Path {
  HOME = '/',
  LOGIN = '/login',
  SIGN_UP = '/register',
  CONTACT = '/contact',
  JOBS = '/jobs',
  ADD_NEW_JOB = '/jobs/add-new-job',
  APPLY = Path.JOBS + '/:id/apply',
  BLOGS = '/blogs',
  MYBLOGS = '/my-blogs',
  ADD_NEW_BLOG = '/blogs/add-new-blog',
  NEWS = '/news',
  MYNEWS = '/my-news',
  ADD_NEWS = '/news/add-new-report',
  ABOUT = '/about',
  POLICIES = '/terms-and-conditions',
  PROFILE = '/profile',
  PROFILE_Edit = '/profile/edit',
  FIND_EMPLOYEE = '/find-employee',
  EDIT_BLOG = '/blogs/edit',
  EDIT_NEWS = '/news/edit',
  EDIT_JOB = '/job/edit',
  COURSES = '/courses',
  VISITS_AND_VIEWS = 'https://s11.flagcounter.com/more/cDCz',
  PURCHASE = '/purchase',
}

export const navLinks = [
  { path: Path.HOME, label: 'navigation.home' },
  { path: Path.JOBS, label: 'navigation.find_job' },
  {
    path: Path.FIND_EMPLOYEE,
    label: 'navigation.find_employee',
    company: true,
  },
  { path: Path.BLOGS, label: 'navigation.blogs' },
  { path: Path.NEWS, label: 'navigation.news' },
  { path: Path.ABOUT, label: 'navigation.about_us' },
  { path: Path.CONTACT, label: 'navigation.contact' },
  { path: Path.COURSES, label: 'navigation.courses' },
  { path: Path.PROFILE, label: 'navigation.profile', protected: true },
];
